#cloud-config

coreos:
  units:
    - name: bootstrap.service
      command: "start"
      content: |
        [Unit]
        Requires=system-config.target
        After=system-config.target

        [Service]
        Type=oneshot
        RemainAfterExit=true
        StandardOutput=journal+console
        Environment=BOOTCFG_URL={{.bootcfg_url}}
        ExecStart=/usr/bin/mkdir -p /var/lib/kubernetes-baremetal
        ExecStart=/usr/bin/wget --no-check-certificate -O /var/lib/kubernetes-baremetal/bootstrap ${BOOTCFG_URL}/assets/kubernetes/scripts/bootstrap
        ExecStart=/usr/bin/chmod +x /var/lib/kubernetes-baremetal/bootstrap
        ExecStart=/var/lib/kubernetes-baremetal/bootstrap
    - name: eth0.network
      runtime: true
      content: |
        [Match]
        Name=en*

        [Network]
        DHCP=yes
